# Generated by Django 4.2.4 on 2023-08-07 23:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Finch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('breed', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, "Eggs don't count as finches yet")])),
            ],
        ),
    ]
