# Generated by Django 4.2.4 on 2023-08-09 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feeding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='feeding date')),
                ('meal', models.CharField(choices=[('B1', '1ˢᵗ Breakfast'), ('B2', '2ⁿᵈ Breakfast'), ('L1', '1ˢᵗ Lunch'), ('L2', '2ⁿᵈ Lunch'), ('D1', '1ˢᵗ Dinner'), ('D2', '2ⁿᵈ Dinner')], default='B1', max_length=2)),
                ('finch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.finch')),
            ],
        ),
    ]
